"""empty message

Revision ID: 88e21efde085
Revises: df76625efa79
Create Date: 2022-04-02 15:30:35.584673

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "88e21efde085"
down_revision = "df76625efa79"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("api_key", sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "api_key")
    # ### end Alembic commands ###
